// AI-generated by Codex/Claude.
`default_nettype none
`timescale 1ns / 1ps

module wb_gpio8_adapter (
    input  wire        clk,
    input  wire        rst,

    input  wire [31:0] wb_adr_i,
    input  wire [31:0] wb_dat_i,
    output wire [31:0] wb_dat_o,
    input  wire [ 3:0] wb_sel_i,
    input  wire        wb_cyc_i,
    input  wire        wb_stb_i,
    input  wire        wb_we_i,
    output wire        wb_ack_o,

    input  wire [ 7:0] gpio_in,
    output wire [ 7:0] gpio_out,
    output wire [ 7:0] gpio_oe,
    output wire        gpio_irq
);

    EF_GPIO8_WB gpio_inst (
        .clk_i  (clk),
        .rst_i  (rst),
        .adr_i  (wb_adr_i),
        .dat_i  (wb_dat_i),
        .dat_o  (wb_dat_o),
        .sel_i  (wb_sel_i),
        .cyc_i  (wb_cyc_i),
        .stb_i  (wb_stb_i),
        .ack_o  (wb_ack_o),
        .we_i   (wb_we_i),
        .IRQ    (gpio_irq),
        .io_in  (gpio_in),
        .io_out (gpio_out),
        .io_oe  (gpio_oe)
    );

endmodule

`default_nettype wire
