// AI-generated by Codex/Claude.
`default_nettype none

module wb_uart16550_adapter (
    input  wire        clk,
    input  wire        rst,

    input  wire [31:0] wb_adr_i,
    input  wire [31:0] wb_dat_i,
    output wire [31:0] wb_dat_o,
    input  wire [ 3:0] wb_sel_i,
    input  wire        wb_cyc_i,
    input  wire        wb_stb_i,
    input  wire        wb_we_i,
    output wire        wb_ack_o,

    output wire        uart_irq,

    input  wire        uart_rx,
    output wire        uart_tx,
    input  wire        uart_cts,
    output wire        uart_rts,
    output wire        uart_dtr,
    input  wire        uart_dsr,
    input  wire        uart_ri,
    input  wire        uart_dcd
);

    wire [2:0] uart_reg_idx = wb_adr_i[4:2];
    // For OpenCores uart_wb (32-bit mode), internal register address is built as:
    // wb_adr_int = {wb_adr_i[4:2], lane_index_from_wb_sel}.
    // Our software uses 4-byte spaced offsets (reg*4), so compress reg index into
    // group bit here and provide lane via wb_sel_i below.
    wire [4:0] uart_adr_5 = {2'b00, uart_reg_idx[2], 2'b00};

    // OpenCores uart_wb derives internal low address bits from wb_sel_i.
    // This core build uses big-endian lane decode (no LITTLE_ENDIAN define):
    // reg0 -> 1000, reg1 -> 0100, reg2 -> 0010, reg3 -> 0001.
    wire [3:0] uart_sel_mapped = (uart_reg_idx[1:0] == 2'b00) ? 4'b1000 :
                                 (uart_reg_idx[1:0] == 2'b01) ? 4'b0100 :
                                 (uart_reg_idx[1:0] == 2'b10) ? 4'b0010 :
                                                                4'b0001;
    wire [31:0] uart_wdata_mapped = {4{wb_dat_i[7:0]}};
    wire [31:0] uart_rdata_raw;

    uart_top uart_inst (
        .wb_clk_i  (clk),
        .wb_rst_i  (rst),
        .wb_adr_i  (uart_adr_5),
        .wb_dat_i  (uart_wdata_mapped),
        .wb_dat_o  (uart_rdata_raw),
        .wb_sel_i  (uart_sel_mapped),
        .wb_we_i   (wb_we_i),
        .wb_stb_i  (wb_stb_i),
        .wb_cyc_i  (wb_cyc_i),
        .wb_ack_o  (wb_ack_o),
        .int_o     (uart_irq),
        .stx_pad_o (uart_tx),
        .srx_pad_i (uart_rx),
        .rts_pad_o (uart_rts),
        .cts_pad_i (uart_cts),
        .dtr_pad_o (uart_dtr),
        .dsr_pad_i (uart_dsr),
        .ri_pad_i  (uart_ri),
        .dcd_pad_i (uart_dcd)
    );

    wire [7:0] uart_rdata_byte = (uart_sel_mapped == 4'b0001) ? uart_rdata_raw[7:0] :
                                 (uart_sel_mapped == 4'b0010) ? uart_rdata_raw[15:8] :
                                 (uart_sel_mapped == 4'b0100) ? uart_rdata_raw[23:16] :
                                                                  uart_rdata_raw[31:24];

    assign wb_dat_o = {24'd0, uart_rdata_byte};

`ifdef FORMAL
    reg f_past_valid = 1'b0;
    initial assume(rst);

    always @(posedge clk) begin
        f_past_valid <= 1'b1;

        if (!f_past_valid)
            assume(rst);

        // --- Wishbone protocol pass-through checks ---

        // 1. Lane mapping: exactly one sel bit is always set
        assert(uart_sel_mapped == 4'b1000 ||
               uart_sel_mapped == 4'b0100 ||
               uart_sel_mapped == 4'b0010 ||
               uart_sel_mapped == 4'b0001);

        // 2. Write data replication: all 4 bytes must be identical
        assert(uart_wdata_mapped[7:0]   == wb_dat_i[7:0]);
        assert(uart_wdata_mapped[15:8]  == wb_dat_i[7:0]);
        assert(uart_wdata_mapped[23:16] == wb_dat_i[7:0]);
        assert(uart_wdata_mapped[31:24] == wb_dat_i[7:0]);

        // 3. Read data output must fit in low 8 bits
        assert(wb_dat_o[31:8] == 24'd0);

        // 4. CYC/STB pass-through: adapter relays, not generates
        //    (wb_stb_i and wb_cyc_i go straight to uart_top)

        // 5. Register index decode consistency
        assert(uart_reg_idx == wb_adr_i[4:2]);

        // 6. Lane decode matches register index LSBs
        if (uart_reg_idx[1:0] == 2'b00) assert(uart_sel_mapped == 4'b1000);
        if (uart_reg_idx[1:0] == 2'b01) assert(uart_sel_mapped == 4'b0100);
        if (uart_reg_idx[1:0] == 2'b10) assert(uart_sel_mapped == 4'b0010);
        if (uart_reg_idx[1:0] == 2'b11) assert(uart_sel_mapped == 4'b0001);

        // 7. Upper address bits are zero in forwarded address
        assert(uart_adr_5[4:3] == 2'b00);
        assert(uart_adr_5[1:0] == 2'b00);
    end
`endif

    wire _unused = &{wb_sel_i, 1'b0};

endmodule

`default_nettype wire
